### ISSUE TITLE
Velocity + NanoLimbo + LibreLogin under docker not working

### ISSUE THREAD

**Issue by ufilme** [kyngs/LibreLogin#151]
Hi, I'm trying to run LibreLogin with Velocity+NanoLimbo under docker but I can't figure out how to make it work. The Velocity container can connect to Paper server and NanoLimbo server container (directly without the plugin) without problems but when I add in the LibreLogin config the NanoLimbo container it doesn't connect.

NanoLimbo (1.6) config:
```
bind:
  ip: ''
  port: 25565
...
infoForwarding:
  type: MODERN
  secret: '***'
```
Velocity (3.2.0-SNAPSHOT-270) config
```
player-info-forwarding-mode = "modern"
authlimbo = "mc-nanolimbo:25565"
main = "mc:25565"
```
LibreLogin (0.17.4) config
```
limbo=[
    authlimbo
]
lobby {
    root=[
        main
    ]
}
```
docker-compose.yaml
```
minecraft:
        container_name: mc
        image: itzg/minecraft-server
        ...
        networks:
          - minecraft-net

nanolimbo:
        container_name: mc-nanolimbo
        image: itzg/minecraft-server
        environment:
          - TYPE=CUSTOM
          - CUSTOM_SERVER=NanoLimbo-1.6.jar
        networks:
          - minecraft-net

velocity:
      container_name: mc-velocity
      image: itzg/bungeecord
      ports:
        - "25565:25577"
      environment:
        - TYPE=VELOCITY
      ...
      networks:
        - minecraft-net
```
Any help is appreciated. Thank you.
